#!/usr/bin/perl

sub triplet1000 {
for( $a = 1; $a < 1000; ++$a )
{
	for( $b = $a; $b < 1000; ++$b )
	{
		for( $c = $b; $c < 1000; ++$c )
		{
			if( ($a + $b + $c == 1000) && ( ($a * $a) + ($b * $b) == ($c * $c))) { return $a * $b * $c; }
		}
	}
}
}

$product = &triplet1000;
print "Product abc is $product\n";
